name: Generate Snake Animation ğŸ

on:
  schedule:
    - cron: "0 0 * * *"  # Executa todos os dias Ã  meia-noite UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout do repositÃ³rio
      - name: Checkout
        uses: actions/checkout@v3

      # Gerar a cobrinha (snake)
      - name: Generate GitHub Snake ğŸ
        uses: Platane/snk@master
        with:
          github_user_name: HenriquePereira777
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Enviar para o branch output
      - name: Push to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
